# Created butnot used in this lab, but you can use it in the next one if you want to mount a configmap as a volume instead of env vars
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lab7.fullname" . }}
  labels:
    {{- include "lab7.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configEnv | nindent 4 }}