apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lab6.fullname" . }}
  labels:
    {{- include "lab6.labels" . | nindent 4 }}
type: Opaque
stringData: 
    {{- toYaml .Values.secretsEnv | nindent 4 }}